// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Data Table": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/arisgk/goa-api-data-table/design
// --out=$(GOPATH)/src/github.com/arisgk/goa-api-data-table
// --version=v1.3.1

package test
